### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by s-ankur** [MUKESHSIHAG/physics-simulation#51]
./boundary_bounce.py
```  
......
File "<unknown>", line 7
    def __init__(self, (x, y), size):
```
Please consider https://www.python.org/dev/peps/pep-3113/
this makes it incompatible with newer versions of python

**Comment by BhanuPrakashNani** [comment]
this issue can be now closed.

**Comment by s-ankur** [comment]
Thanks
